name: nfty
description: Notifications push.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  http: ^1.2.2
  flutter_local_notifications: ^14.0.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  logger: ^2.3.0
  emoji_picker_flutter: ^2.2.0
  device_info_plus: ^10.1.0
  uuid: ^4.4.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  web_socket_channel: ^3.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
