// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8mIBin1if97r2E2qPoURvavfCyNP__tI',
    appId: '1:473895307726:web:d514d4919d58846953439f',
    messagingSenderId: '473895307726',
    projectId: 'pingnotify0',
    authDomain: 'pingnotify0.firebaseapp.com',
    storageBucket: 'pingnotify0.firebasestorage.app',
    measurementId: 'G-HVEEZQXXRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfp6mLS6ahj8Upb_C0nvMfUpLgXRXKcuY',
    appId: '1:473895307726:android:f54e534fb11fb47e53439f',
    messagingSenderId: '473895307726',
    projectId: 'pingnotify0',
    storageBucket: 'pingnotify0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALzS9MRhkhxoTINhFJoaezbIThChl_PDM',
    appId: '1:473895307726:ios:0d25091e37bac66653439f',
    messagingSenderId: '473895307726',
    projectId: 'pingnotify0',
    storageBucket: 'pingnotify0.firebasestorage.app',
    iosBundleId: 'com.example.nfty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALzS9MRhkhxoTINhFJoaezbIThChl_PDM',
    appId: '1:473895307726:ios:0d25091e37bac66653439f',
    messagingSenderId: '473895307726',
    projectId: 'pingnotify0',
    storageBucket: 'pingnotify0.firebasestorage.app',
    iosBundleId: 'com.example.nfty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8mIBin1if97r2E2qPoURvavfCyNP__tI',
    appId: '1:473895307726:web:fcd4d6ac4d6852b453439f',
    messagingSenderId: '473895307726',
    projectId: 'pingnotify0',
    authDomain: 'pingnotify0.firebaseapp.com',
    storageBucket: 'pingnotify0.firebasestorage.app',
    measurementId: 'G-P95157MRRK',
  );

}