// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYJMoVfnlZLZfuEZqrPR9usr8GzUxbvfE',
    appId: '1:935828567019:web:b4bec3e683a5b645a69fae',
    messagingSenderId: '935828567019',
    projectId: 'nfty-push',
    authDomain: 'nfty-push.firebaseapp.com',
    storageBucket: 'nfty-push.appspot.com',
    measurementId: 'G-GP11BCLBBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_b-ZQ2mnqdYTll4NS_WsmcFodNkLLlSQ',
    appId: '1:935828567019:android:bbbcf1d96030b8e7a69fae',
    messagingSenderId: '935828567019',
    projectId: 'nfty-push',
    storageBucket: 'nfty-push.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOSvIAANZ0UpHZPZ-OvUeOR0NFB1IIWS0',
    appId: '1:935828567019:ios:2d616f74c7b69f89a69fae',
    messagingSenderId: '935828567019',
    projectId: 'nfty-push',
    storageBucket: 'nfty-push.appspot.com',
    iosBundleId: 'com.example.nfty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOSvIAANZ0UpHZPZ-OvUeOR0NFB1IIWS0',
    appId: '1:935828567019:ios:2d616f74c7b69f89a69fae',
    messagingSenderId: '935828567019',
    projectId: 'nfty-push',
    storageBucket: 'nfty-push.appspot.com',
    iosBundleId: 'com.example.nfty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYJMoVfnlZLZfuEZqrPR9usr8GzUxbvfE',
    appId: '1:935828567019:web:ec3a7077996566a7a69fae',
    messagingSenderId: '935828567019',
    projectId: 'nfty-push',
    authDomain: 'nfty-push.firebaseapp.com',
    storageBucket: 'nfty-push.appspot.com',
    measurementId: 'G-0Q25SJMJRE',
  );
}
